'use strict';
const entrar=document.querySelector('#entrar-form'),registro=document.querySelector('#registro-form');
function modo(registrarse){entrar.hidden=registrarse;registro.hidden=!registrarse;BAG.aviso('');for(const [id,activo]of [['mostrar-entrar',!registrarse],['mostrar-registro',registrarse]]){const b=document.getElementById(id);b.classList.toggle('primary',activo);b.setAttribute('aria-pressed',String(activo));}}
document.querySelector('#mostrar-entrar').addEventListener('click',()=>modo(false));
document.querySelector('#mostrar-registro').addEventListener('click',()=>modo(true));
for(const [form,accion]of [[entrar,'entrar'],[registro,'registrar']])form.addEventListener('submit',async e=>{e.preventDefault();const b=form.querySelector('[type=submit]');b.disabled=true;try{await BAG.ready;const datos=Object.fromEntries(new FormData(form));if(accion==='registrar'&&datos.password!==datos.confirmar)throw new Error('Las contraseñas no coinciden.');delete datos.confirmar;await BAG.api('cuenta.php',{...datos,accion});form.reset();try{localStorage.setItem('bag-account-change',String(Date.now()));}catch{}location.replace('vista_cuenta.html');}catch(err){BAG.aviso(err.message,true);}finally{b.disabled=false;}});
document.querySelector('#cerrar-cuenta').addEventListener('click',async e=>{e.currentTarget.disabled=true;try{await BAG.api('cuenta.php',{accion:'salir'});try{localStorage.setItem('bag-account-change',String(Date.now()));}catch{}location.replace('vista_cuenta.html');}catch(err){BAG.aviso(err.message,true);e.target.disabled=false;}});
BAG.ready.then(s=>{if(!s)return;const auth=s.account.authenticated;document.querySelector('#acceso').hidden=auth;document.querySelector('#mi-cuenta').hidden=!auth;if(auth){document.querySelector('#saludo-cuenta').textContent='Hola, '+s.profile.nombre;document.querySelector('#correo-cuenta').textContent=s.account.email;}else {for(const k of ['region','idioma','tema'])registro.elements[k].value=s.profile[k];modo(new URLSearchParams(location.search).get('modo')==='registro');}});

for(const k of ['tema','idioma'])registro.elements[k].addEventListener('change',()=>BAGConfig.aplicar({[k]:registro.elements[k].value},false));
