CREATE DATABASE IF NOT EXISTS bag CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bag;
CREATE TABLE IF NOT EXISTS usuarios (
 id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(80) NOT NULL DEFAULT 'Invitado', edad TINYINT UNSIGNED NULL, clasificacion_maxima VARCHAR(3) NOT NULL DEFAULT 'A', fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS preferencias (
 id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL UNIQUE, plataforma VARCHAR(40) NOT NULL DEFAULT '', genero VARCHAR(40) NOT NULL DEFAULT '', modo_juego VARCHAR(20) NOT NULL DEFAULT 'Ambos', fecha_actualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS conversaciones (
 id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL, titulo VARCHAR(120) NOT NULL DEFAULT 'Nuevo chat', fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, fecha_actualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS mensajes (
 id INT AUTO_INCREMENT PRIMARY KEY, conversacion_id INT NOT NULL, emisor ENUM('usuario','bag') NOT NULL, mensaje TEXT NOT NULL, datos MEDIUMTEXT NULL, fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (conversacion_id) REFERENCES conversaciones(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS busquedas (
 id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL, termino VARCHAR(500) NOT NULL, tipo_busqueda VARCHAR(50) NOT NULL, fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS cuentas (
 usuario_id INT PRIMARY KEY,
 correo VARCHAR(254) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 creada DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS acceso_limites (
 clave CHAR(64) PRIMARY KEY, intentos INT NOT NULL DEFAULT 0,
 inicio DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS configuracion_usuario (usuario_id INT PRIMARY KEY, region CHAR(2) NOT NULL DEFAULT 'MX', idioma VARCHAR(2) NOT NULL DEFAULT 'es', tema VARCHAR(8) NOT NULL DEFAULT 'oscuro', FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE) ENGINE=InnoDB;
